const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Behaviors.Sin,
		C3.Behaviors.Tween,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Plugins.Audio,
		C3.Plugins.Touch,
		C3.Plugins.Mouse,
		C3.Plugins.Browser,
		C3.Behaviors.Physics,
		C3.Behaviors.DragnDrop,
		C3.Plugins.AJAX,
		C3.Plugins.Shape3D,
		C3.Behaviors.MoveTo,
		C3.Plugins.Touch.Cnds.OnDoubleTapGestureObject,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Browser.Exps.QueryParam,
		C3.Plugins.Browser.Exps.ExecJS,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.OnEnded,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.System.Acts.NextPrevLayout,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Touch.Cnds.OnDoubleTapGesture,
		C3.Behaviors.DragnDrop.Cnds.OnDrop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.DragnDrop.Cnds.OnDragStart,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.AJAX.Acts.Post,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Behaviors.DragnDrop.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Sprite.Acts.SetAnim
	];
};
self.C3_JsPropNameTable = [
	{A0: 0},
	{A1: 0},
	{A2: 0},
	{A3: 0},
	{B1: 0},
	{C1: 0},
	{C2: 0},
	{Sine: 0},
	{C3: 0},
	{G: 0},
	{B2: 0},
	{D1: 0},
	{Tween: 0},
	{D2: 0},
	{D3: 0},
	{D4: 0},
	{E1: 0},
	{E2: 0},
	{E3: 0},
	{E4: 0},
	{E5: 0},
	{E6: 0},
	{E8: 0},
	{F5: 0},
	{F2: 0},
	{F3: 0},
	{F1: 0},
	{copyright: 0},
	{credits: 0},
	{storytext: 0},
	{total: 0},
	{layout: 0},
	{arrow: 0},
	{Audio: 0},
	{Touch: 0},
	{Mouse: 0},
	{Browser: 0},
	{smoke: 0},
	{debug: 0},
	{Physics: 0},
	{ground: 0},
	{fire: 0},
	{wolf: 0},
	{DragDrop: 0},
	{finger: 0},
	{storyframe: 0},
	{storytoggle: 0},
	{previous: 0},
	{AJAX: 0},
	{FFLogoTransparent: 0},
	{table_yellow_background: 0},
	{cup_shadow: 0},
	{spilling_left_5: 0},
	{table_background2: 0},
	{accident: 0},
	{table_yellow_background2: 0},
	{"3DShape": 0},
	{Sprite: 0},
	{MoveTo: 0},
	{teacupred: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{PPP_: 0},
	{background_blue_blotches_: 0},
	{Sprite6: 0},
	{fae_terrified: 0},
	{balloon: 0},
	{oneQuill: 0},
	{backpack: 0},
	{book: 0},
	{crayons: 0},
	{folder: 0},
	{pen: 0},
	{backgroundBedroom: 0},
	{pop: 0},
	{background_field: 0},
	{background_blue_fade: 0},
	{background_yellow_gradient: 0},
	{Fae_angry: 0},
	{Fae_joy: 0},
	{table_background: 0},
	{nail: 0},
	{protect_: 0},
	{protect_2: 0},
	{seatbelt: 0},
	{backpack_front_piece: 0},
	{backpack_zipping: 0},
	{inbackpack: 0},
	{supplies: 0},
	{startDate: 0},
	{timer: 0},
	{state: 0},
	{story: 0},
	{langtoggle: 0},
	{next: 0},
	{t: 0},
	{u: 0},
	{m: 0},
	{b: 0}
];

self.InstanceType = {
	A0: class extends self.ITiledBackgroundInstance {},
	A1: class extends self.ITiledBackgroundInstance {},
	A2: class extends self.ITiledBackgroundInstance {},
	A3: class extends self.ITiledBackgroundInstance {},
	B1: class extends self.ITiledBackgroundInstance {},
	C1: class extends self.ITiledBackgroundInstance {},
	C2: class extends self.ITiledBackgroundInstance {},
	C3: class extends self.ITiledBackgroundInstance {},
	G: class extends self.ITiledBackgroundInstance {},
	B2: class extends self.ITiledBackgroundInstance {},
	D1: class extends self.ITiledBackgroundInstance {},
	D2: class extends self.ITiledBackgroundInstance {},
	D3: class extends self.ITiledBackgroundInstance {},
	D4: class extends self.ITiledBackgroundInstance {},
	E1: class extends self.ITiledBackgroundInstance {},
	E2: class extends self.ITiledBackgroundInstance {},
	E3: class extends self.ITiledBackgroundInstance {},
	E4: class extends self.ITiledBackgroundInstance {},
	E5: class extends self.ITiledBackgroundInstance {},
	E6: class extends self.ITiledBackgroundInstance {},
	E8: class extends self.ITiledBackgroundInstance {},
	F5: class extends self.ITiledBackgroundInstance {},
	F2: class extends self.ITiledBackgroundInstance {},
	F3: class extends self.ITiledBackgroundInstance {},
	F1: class extends self.ITiledBackgroundInstance {},
	copyright: class extends self.ITextInstance {},
	credits: class extends self.ITextInstance {},
	storytext: class extends self.ITextInstance {},
	total: class extends self.ITextInstance {},
	layout: class extends self.ITextInstance {},
	arrow: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	smoke: class extends self.ISpriteInstance {},
	debug: class extends self.ISpriteInstance {},
	ground: class extends self.ISpriteInstance {},
	fire: class extends self.ISpriteInstance {},
	wolf: class extends self.ISpriteInstance {},
	finger: class extends self.ISpriteInstance {},
	storyframe: class extends self.ISpriteInstance {},
	storytoggle: class extends self.ISpriteInstance {},
	previous: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	FFLogoTransparent: class extends self.ISpriteInstance {},
	table_yellow_background: class extends self.ISpriteInstance {},
	cup_shadow: class extends self.ISpriteInstance {},
	spilling_left_5: class extends self.ISpriteInstance {},
	table_background2: class extends self.ISpriteInstance {},
	accident: class extends self.ISpriteInstance {},
	table_yellow_background2: class extends self.ISpriteInstance {},
	_3DShape: class extends self.I3DShapeInstance {},
	Sprite: class extends self.ISpriteInstance {},
	teacupred: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	PPP_: class extends self.ISpriteInstance {},
	background_blue_blotches_: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	fae_terrified: class extends self.ISpriteInstance {},
	balloon: class extends self.ISpriteInstance {},
	oneQuill: class extends self.ISpriteInstance {},
	backpack: class extends self.ISpriteInstance {},
	book: class extends self.ISpriteInstance {},
	crayons: class extends self.ISpriteInstance {},
	folder: class extends self.ISpriteInstance {},
	pen: class extends self.ISpriteInstance {},
	backgroundBedroom: class extends self.ISpriteInstance {},
	pop: class extends self.ISpriteInstance {},
	background_field: class extends self.ISpriteInstance {},
	background_blue_fade: class extends self.ISpriteInstance {},
	background_yellow_gradient: class extends self.ISpriteInstance {},
	Fae_angry: class extends self.ISpriteInstance {},
	Fae_joy: class extends self.ISpriteInstance {},
	table_background: class extends self.ISpriteInstance {},
	nail: class extends self.ISpriteInstance {},
	protect_: class extends self.ISpriteInstance {},
	protect_2: class extends self.ISpriteInstance {},
	seatbelt: class extends self.ISpriteInstance {},
	backpack_front_piece: class extends self.ISpriteInstance {},
	backpack_zipping: class extends self.ISpriteInstance {},
	inbackpack: class extends self.ISpriteInstance {},
	supplies: class extends self.ISpriteInstance {}
}